spring:
  discovery:
    enabled: true
    main:
      allow-bean-definition-overriding: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true