spring:
  application:
    name: reservation-service  # 👈 À ajouter obligatoirement

  datasource:
    url: jdbc:mysql://localhost:3306/easytrip_db?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  discovery:
    enabled: true

  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
