services:
  destination-service:
    image: dhiashayeb017/gestion-destination-service:latest
    ports:
      - "8087:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - keycloak
    networks:
      - keycloak

  postgresql:
    image: postgres:16
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_DB=keycloak
      - POSTGRES_PASSWORD=SUPERsecret
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    command: start-dev
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgresql:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=SUPERsecret
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_HTTP_PORT=8080
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
    ports:
      - "8080:8080"
    networks:
      - keycloak
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  keycloak:
    driver: bridge

volumes:
  postgresql_data: